### ISSUE TITLE
Whitelabel claiming page

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/Linkdrop-Webapp#19]
# Description

Several users of eth2 and volca.tech has requested to custom the claiming page flow

# Subtasks included

- [ ] Split claiming flow into dedicated component suitable for support white-label solutions
- [ ] Split claiming story-book into dedicated component 

# Definition of done

- [ ] First custom claiming page is delivered

# Reviewer

@Dobrokhvalov

**Comment by seichris** [comment]
## what do airdrop projects want on their claim page?

### social / kyc
- join telegram
- join discord
- follow on twitter
- ...
- verify mail
- full kyc with passport

### join an IEO site
- e.g. latoken, gate.io

### more info
- education about the project
- steps to take to get the airdrop
- referral scheme
