### ISSUE TITLE
Create mock-up of Linkdrop Pro

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/Linkdrop-Webapp#2]
# Description

This issue serves as the master-issue for Linkdrop PRO mock-ups needed for the Linkdrop PRO mvp milestone. For Analytics please see #24.

# Subtasks included

- [x] Freemium Landing Page Demo flow
- [ ] Linkdrop PRO dashboard and campaign settings
- [ ] Linkdrop PRO linkdrop generation flow
- [x] Linkdrop Claiming flow

# Definition of done

Above screens are done, fully handed-over, and the implementation has started.

# Reviewer

@seichris

**Comment by seichris** [comment]
ping me when the design's ready

**Comment by artignatev** [comment]
For demo webapp we need another logo, not the one that for Linkdrop Protocol. Like what we have for Eth2.io

**Comment by Kisgus** [comment]
Okay, the current eth2 logo( just on black background instead of blue) would maybe be okay then @artignatyev ?

**Comment by artignatev** [comment]
Something like that, I'll figure it out

**Comment by Kisgus** [comment]
Merged with https://github.com/LinkdropProtocol/Linkdrop-Webapp/issues/5

**Comment by Kisgus** [comment]
Moved to mono-repo
