### ISSUE TITLE
Paid access to files & hosted files.

### ISSUE THREAD

**Issue by seichris** [LinkdropProtocol/Linkdrop-Webapp#20]
# Description

Allow users to get for access to a file, which can be 1. uploaded to IPFS via our platform or 2. shown behind a link (e.g. get paid for mega.nz file pw).

# Subtasks included

- [x] write user story
- [x] make design: https://www.figma.com/file/cAZC7IPUn1N1soraUWLmIxCw/Linkdrop-Pro?node-id=57%3A316

# Definition of done

- [ ] Feedback by the team if we need this or not.

# Reviewer

@Dobrokhvalov

**Comment by seichris** [comment]
## user story

A content creator wants to get paid for his creation, but existing solutions like bandcamp or patreon are too heavy. She simple wants a link she can share in her conversations with fans.

She goes to our site, enters the password to the new song she uploaded to her GDrive. The linkdrop server serves her a unique link, which she now shares with her closest fans.

**Comment by Kisgus** [comment]
Moved to mono-repo
