### ISSUE TITLE
Linkdrop Analytics

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/Linkdrop-Webapp#24]
# Description

We need to define:

- Data collected
- Data visible

# Subtasks included

- [x] Create list of what we can collect
- [x] Decide on which things and how we will collect for Analytics page  v1
- [ ] Implement front-end
- [ ] Implement back-end

# Definition of done

- [ ] The desired analytics are collected and presented in a nice format with pretty visualizations

# After done

- [ ] Open new issue on asking customers on their needs for analytics

# Reviewer

@Kisgus

**Comment by Kisgus** [comment]
See this document for analytics overview:

https://docs.google.com/document/d/1eyuDaUBinIKk7AH514NzEbRfLlFWaMlijwbk_khJzk4/edit

**Comment by Kisgus** [comment]
Moved to monorepo
